[[main]]
  name = "journal"
  pageRef = "journal"
  weight = 10

[[main]]
  name = "visual"
  pageRef = "visual"
  weight = 20

[[main]]
  name = "health"
  pageRef = "health"
  weight = 30

[[main]]
  name = "about"
  pageRef = "about"
  weight = 40

